### ISSUE TITLE
Readme: Typo in "Resetting a to-many, ref-typed relationship" section

### ISSUE THREAD

**Issue by aeberts** [vvvvalvalval/datofu#1]
Hi there,

In the example of the section "Resetting a to-many, ref-typed relationship" of `Readme.md` there appears to be a typo: 

It's possible that I don't understand the library well enough, but should the result of the second query (after resetting the tags) be:

`=> ["datomic" "birds"]`?

and not

`=> ["datomic" "flowers"]`?

**Comment by vvvvalvalval** [comment]
I guessed I just hit a new record of latency in addressing an issue! You're right, I just fixed it, thanks.
